using MechanicalDesigns.Application.Advertisements;using MechanicalDesigns.Domain.Entities;using MechanicalDesigns.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;
namespace MechanicalDesigns.Infrastructure.Advertisements;
public sealed class AdvertisementService(ApplicationDbContext db):IAdvertisementService{
 public async Task<IReadOnlyList<AdvertisementResponse>>PublicAsync(CancellationToken ct){var n=DateTimeOffset.UtcNow;return(await db.Advertisements.AsNoTracking().Where(x=>x.IsActive&&(x.StartDate==null||x.StartDate<=n)&&(x.EndDate==null||x.EndDate>=n)).OrderBy(x=>x.DisplayOrder).ToListAsync(ct)).Select(Map).ToList();}
 public async Task<IReadOnlyList<AdvertisementResponse>>AdminAsync(CancellationToken ct)=>(await db.Advertisements.IgnoreQueryFilters().AsNoTracking().OrderBy(x=>x.DisplayOrder).ToListAsync(ct)).Select(Map).ToList();
 public async Task<AdvertisementResponse>CreateAsync(AdvertisementRequest r,CancellationToken ct){Validate(r);var x=Apply(new Advertisement(),r);db.Advertisements.Add(x);await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<AdvertisementResponse?>UpdateAsync(Guid id,AdvertisementRequest r,CancellationToken ct){Validate(r);var x=await db.Advertisements.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return null;Apply(x,r);await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<bool>StatusAsync(Guid id,bool a,CancellationToken ct){var x=await db.Advertisements.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return false;x.IsActive=a;await db.SaveChangesAsync(ct);return true;}
 public async Task<bool>DeleteAsync(Guid id,CancellationToken ct){var x=await db.Advertisements.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return false;x.IsDeleted=true;x.DeletedAt=DateTimeOffset.UtcNow;x.IsActive=false;await db.SaveChangesAsync(ct);return true;}
 private static void Validate(AdvertisementRequest r){if(!Uri.TryCreate(r.ImageUrl,UriKind.Absolute,out _))throw new ArgumentException("ImageUrl must be absolute.");if(r.EndDate<r.StartDate)throw new ArgumentException("EndDate must be after StartDate.");}
 private static Advertisement Apply(Advertisement x,AdvertisementRequest r){x.TitleAr=r.TitleAr.Trim();x.TitleEn=r.TitleEn.Trim();x.ImageUrl=r.ImageUrl.Trim();x.MobileImageUrl=r.MobileImageUrl?.Trim();x.LinkUrl=r.LinkUrl?.Trim();x.DisplayOrder=Math.Max(0,r.DisplayOrder);x.StartDate=r.StartDate;x.EndDate=r.EndDate;return x;}
 private static AdvertisementResponse Map(Advertisement x)=>new(x.Id,x.TitleAr,x.TitleEn,x.ImageUrl,x.MobileImageUrl,x.LinkUrl,x.DisplayOrder,x.StartDate,x.EndDate,x.IsActive);}
