using System.Security.Cryptography;using MechanicalDesigns.Application.Admin;using MechanicalDesigns.Application.Common;using MechanicalDesigns.Domain.Entities;using MechanicalDesigns.Domain.Enums;using MechanicalDesigns.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;
namespace MechanicalDesigns.Infrastructure.Admin;
public sealed class AdminUserService(ApplicationDbContext db):IAdminUserService{
 public async Task<IReadOnlyList<AdminUserResponse>>ListAsync(string? s,CancellationToken ct){var q=db.Users.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(s)){s=s.Trim();q=q.Where(x=>EF.Functions.ILike(x.Name,$"%{s}%")||EF.Functions.ILike(x.Email,$"%{s}%")||EF.Functions.ILike(x.PhoneNumber!, $"%{s}%"));}return(await q.OrderByDescending(x=>x.CreatedAt).ToListAsync(ct)).Select(Map).ToList();}
 public async Task<AdminUserResponse?>GetAsync(Guid id,CancellationToken ct){var x=await db.Users.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);return x is null?null:Map(x);}
 public async Task<AdminUserResponse>CreateAdminAsync(AdminCreateRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Email)||r.Password.Length<12)throw new ArgumentException("Name, email, and a password of at least 12 characters are required.");var email=r.Email.Trim().ToLowerInvariant();if(await db.Users.AnyAsync(x=>x.Email==email,ct))throw new ConflictException("An account with this email already exists.");var user=new User{Name=r.Name.Trim(),Email=email,PasswordHash=HashPassword(r.Password),PhoneNumber=r.PhoneNumber?.Trim(),WhatsAppNumber=r.WhatsAppNumber?.Trim(),EmailVerified=true,Role=UserRole.Admin};db.Users.Add(user);await db.SaveChangesAsync(ct);return Map(user);}
 public async Task<bool>BlockAsync(Guid id,bool b,CancellationToken ct){var x=await db.Users.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return false;x.IsBlocked=b;await db.SaveChangesAsync(ct);return true;}
 private static string HashPassword(string password){var salt=RandomNumberGenerator.GetBytes(16);var hash=Rfc2898DeriveBytes.Pbkdf2(password,salt,600_000,HashAlgorithmName.SHA512,32);return $"v1.{Convert.ToBase64String(salt)}.{Convert.ToBase64String(hash)}";}
 private static AdminUserResponse Map(User x)=>new(x.Id,x.Name,x.Email,x.PhoneNumber,x.WhatsAppNumber,x.EmailVerified,x.IsBlocked,x.Role.ToString(),x.CreatedAt);}
