using MechanicalDesigns.Application.Common;
using MechanicalDesigns.Application.Orders;
using MechanicalDesigns.Domain.Entities;
using MechanicalDesigns.Domain.Enums;
using MechanicalDesigns.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
namespace MechanicalDesigns.Infrastructure.Orders;
public sealed class OrderService(ApplicationDbContext db):IOrderService
{
 public async Task<OrderResponse>CreateAsync(Guid u,OrderCreateRequest r,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var cart=await db.Carts.Include(x=>x.Items).ThenInclude(x=>x.Product).SingleOrDefaultAsync(x=>x.UserId==u,ct)??throw new ConflictException("Cart is empty.");if(cart.Items.Count==0)throw new ConflictException("Cart is empty.");foreach(var i in cart.Items){if(!i.Product.IsActive||i.Product.StockQuantity<i.Quantity)throw new ConflictException($"Product '{i.Product.TitleEn}' is unavailable or out of stock.");}var governorateName=r.Governorate.Trim();var delivery=await db.GovernorateDeliveryFees.SingleOrDefaultAsync(x=>x.IsActive&&x.DeliveryFee!=null&&EF.Functions.ILike(x.Name,governorateName),ct)??throw new ConflictException("Delivery is not available for the selected governorate.");var subtotal=cart.Items.Sum(x=>x.Product.Price*x.Quantity);var shipping=delivery.DeliveryFee!.Value;var order=new Order{UserId=u,OrderNumber=$"MD-{DateTime.UtcNow:yyyy}-{Guid.NewGuid().ToString("N")[..8].ToUpperInvariant()}",CustomerName=r.CustomerName.Trim(),PhoneNumber=r.PhoneNumber.Trim(),WhatsAppNumber=r.WhatsAppNumber?.Trim(),Address=r.Address.Trim(),City=r.City.Trim(),Governorate=delivery.Name,Subtotal=subtotal,ShippingCost=shipping,Total=subtotal+shipping,CustomerNotes=r.CustomerNotes?.Trim()};foreach(var i in cart.Items){i.Product.StockQuantity-=i.Quantity;order.Items.Add(new OrderItem{ProductId=i.ProductId,ProductTitleAr=i.Product.TitleAr,ProductTitleEn=i.Product.TitleEn,UnitPrice=i.Product.Price,Quantity=i.Quantity,TotalPrice=i.Product.Price*i.Quantity});}db.Orders.Add(order);db.CartItems.RemoveRange(cart.Items);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(order);}
 public async Task<IReadOnlyList<OrderResponse>>GetMineAsync(Guid u,CancellationToken ct)=>await db.Orders.AsNoTracking().Include(x=>x.Items).Where(x=>x.UserId==u).OrderByDescending(x=>x.CreatedAt).Select(x=>new OrderResponse(x.Id,x.OrderNumber,x.Subtotal,x.ShippingCost,x.Total,x.PaymentStatus.ToString(),x.OrderStatus.ToString(),x.CreatedAt,x.Items.Select(i=>new OrderItemResponse(i.Id,i.ProductId,i.ProductTitleAr,i.ProductTitleEn,i.UnitPrice,i.Quantity,i.TotalPrice,i.Status.ToString())).ToList(),x.CustomerName,x.PhoneNumber,x.WhatsAppNumber,x.Address,x.City,x.Governorate,x.CustomerNotes,x.UserId)).ToListAsync(ct);
 public async Task<OrderResponse?>GetMineAsync(Guid u,Guid id,CancellationToken ct)=>(await GetMineAsync(u,ct)).SingleOrDefault(x=>x.Id==id);
 public async Task<IReadOnlyList<OrderResponse>>GetAdminAsync(string? status,CancellationToken ct){var q=db.Orders.AsNoTracking().Include(x=>x.Items).AsQueryable();if(Enum.TryParse<OrderStatus>(status,true,out var s))q=q.Where(x=>x.OrderStatus==s);var orders=await q.OrderByDescending(x=>x.CreatedAt).ToListAsync(ct);return orders.Select(Map).ToList();}
 public async Task<OrderResponse?>GetAdminAsync(Guid id,CancellationToken ct){var x=await db.Orders.AsNoTracking().Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id,ct);return x is null?null:Map(x);}
 public async Task<bool>SetStatusAsync(Guid id,Guid adminId,OrderStatusUpdateRequest r,CancellationToken ct){if(!Enum.TryParse<OrderStatus>(r.Status,true,out var s))throw new ArgumentException("Invalid order status.");var o=await db.Orders.SingleOrDefaultAsync(x=>x.Id==id,ct);if(o is null)return false;if(o.OrderStatus!=s){db.OrderStatusHistories.Add(new OrderStatusHistory{OrderId=id,OldStatus=o.OrderStatus,NewStatus=s,ChangedByUserId=adminId,Notes=r.Notes?.Trim()});o.OrderStatus=s;await db.SaveChangesAsync(ct);}return true;}
 public async Task<bool>SetPaymentStatusAsync(Guid id,PaymentStatusUpdateRequest r,CancellationToken ct){if(!Enum.TryParse<PaymentStatus>(r.Status,true,out var s))throw new ArgumentException("Invalid payment status.");var o=await db.Orders.SingleOrDefaultAsync(x=>x.Id==id,ct);if(o is null)return false;o.PaymentStatus=s;await db.SaveChangesAsync(ct);return true;}
 public async Task<bool>SetItemStatusAsync(Guid orderId,Guid itemId,OrderItemStatusUpdateRequest r,CancellationToken ct){if(!Enum.TryParse<OrderItemStatus>(r.Status,true,out var s))throw new ArgumentException("Invalid order item status.");var i=await db.OrderItems.SingleOrDefaultAsync(x=>x.OrderId==orderId&&x.Id==itemId,ct);if(i is null)return false;i.Status=s;await db.SaveChangesAsync(ct);return true;}
 private static OrderResponse Map(Order x)=>new(x.Id,x.OrderNumber,x.Subtotal,x.ShippingCost,x.Total,x.PaymentStatus.ToString(),x.OrderStatus.ToString(),x.CreatedAt,x.Items.Select(i=>new OrderItemResponse(i.Id,i.ProductId,i.ProductTitleAr,i.ProductTitleEn,i.UnitPrice,i.Quantity,i.TotalPrice,i.Status.ToString())).ToList(),x.CustomerName,x.PhoneNumber,x.WhatsAppNumber,x.Address,x.City,x.Governorate,x.CustomerNotes,x.UserId);
}
